### PR TITLE
Rewrite standards copy for accuracy.

### PR DESCRIPTION
**Pull request by Vinnl**
Recreated @RubenVerborgh's PR from https://github.com/solid/solidproject.org/pull/26.

### CODE REVIEW

**Comment by RubenVerborgh** [comment]
Thanks. How does the process work exactly? Is this repo staging?

**Comment by Mitzi-Laszlo** [comment]
https://github.com/solid/process#solidprojectorg-website

**Comment by Vinnl** [comment]
Yes, the tl;dr is that this is the staging repository, except for This Week in Solid.

**Comment by RubenVerborgh** [comment]
@NSeydoux Thanks a lot; took your title suggestion and integrated your text suggestions.

**Pull request closed without merging**
