### PR TITLE
added Example config for NSS on root-server

### PR DESCRIPTION
**Pull request by ewingson**
@Vinnl @jaxoncreed @Mitzi-Laszlo 

added extensive documentation, capitalization...

### CODE REVIEW

**Comment by ewingson** [comment]
@NSeydoux 

thanx for your feedback. will check an alternative node howto.
I' m not yet familiar with jekyll. perhaps lets make two new pages for apache/nginx setup.
for the nginx setup we could ask @etcware 

and let' s stay closely synced with @Vinnl @jaxoncreed and @Mitzi-Laszlo

**Comment by NSeydoux** [comment]
If you are okay with this suggestion, I can merge your changes in as soon as you updated the node howto, and i can take care of moving the Apache setup in a different page if you're not comfortable with Jekyll. This way, it will create a precedent showing how to do it for future contributions, for instance regarding nginx.

**Comment by ewingson** [comment]
okay, very cool. I' ll change the node link when I' m home in a few hours. furthermore I' ll look out for @etcware in the gitter channel and appreciate your help. experiments with jekyll are To-Do for me.

will let you know here in the comments as soon as I' m ready to merge. ;-)

**Comment by ewingson** [comment]
@NSeydoux are you okay with the changes ?
have used an eglish version now...

**Comment by NSeydoux** [comment]
Great, thanks again. I'll merge this in, and update the content to make the apache conf a separate page.

**Comment by ewingson** [comment]
the node link would need to be formatted as a href with jekyll syntax.....

**Pull request merged**
